CREATE DATABASE IF NOT EXISTS college_erp;
USE college_erp;

CREATE TABLE IF NOT EXISTS students (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE, password VARCHAR(100), course VARCHAR(160) NOT NULL,
  year VARCHAR(20) NOT NULL, status VARCHAR(30) DEFAULT 'Active'
);
CREATE TABLE IF NOT EXISTS teachers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120), email VARCHAR(160), password VARCHAR(100),
  department VARCHAR(100), subject VARCHAR(120)
);
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(40) UNIQUE,
  name VARCHAR(160), duration VARCHAR(40)
);
